clc;
close all;
clear all;
G_Ch=load('G_Ch.mat');
G_Ch_eq=load('G_Ch_eq.mat');
R_Ch=load('R_Ch.mat');
R_Ch_eq=load('R_Ch_eq.mat');
SNR_max=length(G_Ch.ber)-1;
semilogy(0:SNR_max,G_Ch.ber,'--g*');
hold on;
semilogy(0:SNR_max,G_Ch_eq.ber_equilibrium,'--r*');
hold on;
semilogy(0:SNR_max,R_Ch.ber,'--k*');
hold on;
semilogy(0:SNR_max,R_Ch_eq.ber_equilibrium,'--c*');
legend('无衰落、未均衡','无衰落、已均衡','有衰落、未均衡','有衰落、已均衡');
xlabel('E_{b}/n_{0}');
ylabel('Pe');
title('有无衰落及均衡前后系统误码率曲线比较');
grid on;