clc;
close all;
clear all;
rectangle=load('rectangle.mat');
rectangle_Gray=load('rectangle_Gray.mat');
circle=load('circle.mat');
circle_Gray=load('circle_Gray.mat');
SNR_max=length(rectangle.ber_equilibrium)-1;
semilogy(0:SNR_max,rectangle.ber_equilibrium,'--r*');
hold on;
semilogy(0:SNR_max,rectangle_Gray.ber_equilibrium,'--g*');
hold on;
semilogy(0:SNR_max,circle.ber_equilibrium,'--c*');
hold on;
semilogy(0:SNR_max,circle_Gray.ber_equilibrium,'--k*');
legend('方形映射+二进制码','方形映射+格雷编码','环形映射+二进制码','环形映射+格雷编码');
xlabel('E_{b}/n_{0}');
ylabel('Pe');
title('16QAM调制时不同调制方案对误码率的影响');
grid on;